packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@google/genai": true
  core-js: true
  esbuild: true
  protobufjs: true
  sharp: true
  workerd: true
onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@google/genai"
  - core-js
  - esbuild
  - oxc-resolver
  - protobufjs
  - rolldown
  - sharp
  - unrs-resolver
  - workerd
minimumReleaseAgeExclude:
  - daisyui
  - '@cloudflare/workers-types@5.20260705.1'
