packages:
  - "."
onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@google/genai"
  - core-js
  - esbuild
  - oxc-resolver
  - protobufjs
  - rolldown
  - sharp
  - unrs-resolver
  - workerd
minimumReleaseAgeExclude:
  - daisyui
